apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers: 
        - name: event-bus
          image: rkbhardwaj88/event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv #Name of the service
spec:
  type: ClusterIP #type of service (ClusterIP, Node Port, Load Balancer, default is ClusterIP)
  selector:
    app: event-bus #name of the app for which the service is created
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 #This the port for the node service
      targetPort: 4005  #This is port where the posts node service is listening - refernce posts/index.js


