apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers: 
        - name: posts
          image: rkbhardwaj88/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv #Name of the service
spec:
  type: ClusterIP #type of service (ClusterIP, Node Port, Load Balancer)
  selector:
    app: posts #name of the app for which the service is created
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #This the port for the node service
      targetPort: 4000  #This is port where the posts node service is listening - refernce posts/index.js


