apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers: 
        - name: query
          image: rkbhardwaj88/query
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv #Name of the service
spec:
  type: ClusterIP #type of service (ClusterIP, Node Port, Load Balancer)
  selector:
    app: query #name of the app for which the service is created
  ports:
    - name: query
      protocol: TCP
      port: 4002 #This the port for the node service
      targetPort: 4002  #This is port where the query node service is listening - refernce query/index.js

